/**
 * @fileoverview gRPC-Web generated client stub for user_profile
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v3.21.12
// source: protos/user_profile.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.user_profile = require('./user_profile_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.user_profile.UserProfileClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.user_profile.UserProfilePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user_profile.UserLogInfo,
 *   !proto.user_profile.StatusResponse>}
 */
const methodDescriptor_UserProfile_register_user = new grpc.web.MethodDescriptor(
  '/user_profile.UserProfile/register_user',
  grpc.web.MethodType.UNARY,
  proto.user_profile.UserLogInfo,
  proto.user_profile.StatusResponse,
  /**
   * @param {!proto.user_profile.UserLogInfo} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user_profile.StatusResponse.deserializeBinary
);


/**
 * @param {!proto.user_profile.UserLogInfo} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user_profile.StatusResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user_profile.StatusResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user_profile.UserProfileClient.prototype.register_user =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user_profile.UserProfile/register_user',
      request,
      metadata || {},
      methodDescriptor_UserProfile_register_user,
      callback);
};


/**
 * @param {!proto.user_profile.UserLogInfo} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user_profile.StatusResponse>}
 *     Promise that resolves to the response
 */
proto.user_profile.UserProfilePromiseClient.prototype.register_user =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user_profile.UserProfile/register_user',
      request,
      metadata || {},
      methodDescriptor_UserProfile_register_user);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user_profile.UserLogInfo,
 *   !proto.user_profile.StatusResponse>}
 */
const methodDescriptor_UserProfile_get_user_profile = new grpc.web.MethodDescriptor(
  '/user_profile.UserProfile/get_user_profile',
  grpc.web.MethodType.UNARY,
  proto.user_profile.UserLogInfo,
  proto.user_profile.StatusResponse,
  /**
   * @param {!proto.user_profile.UserLogInfo} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user_profile.StatusResponse.deserializeBinary
);


/**
 * @param {!proto.user_profile.UserLogInfo} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user_profile.StatusResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user_profile.StatusResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user_profile.UserProfileClient.prototype.get_user_profile =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user_profile.UserProfile/get_user_profile',
      request,
      metadata || {},
      methodDescriptor_UserProfile_get_user_profile,
      callback);
};


/**
 * @param {!proto.user_profile.UserLogInfo} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user_profile.StatusResponse>}
 *     Promise that resolves to the response
 */
proto.user_profile.UserProfilePromiseClient.prototype.get_user_profile =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user_profile.UserProfile/get_user_profile',
      request,
      metadata || {},
      methodDescriptor_UserProfile_get_user_profile);
};


module.exports = proto.user_profile;

