# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_profile.user_profile_pb2 as user__profile__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in user_profile_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserProfileStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register_user = channel.unary_unary(
                '/user_profile.UserProfile/register_user',
                request_serializer=user__profile__pb2.UserLogInfo.SerializeToString,
                response_deserializer=user__profile__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.get_user_profile = channel.unary_unary(
                '/user_profile.UserProfile/get_user_profile',
                request_serializer=user__profile__pb2.UserLogInfo.SerializeToString,
                response_deserializer=user__profile__pb2.StatusResponse.FromString,
                _registered_method=True)


class UserProfileServicer(object):
    """Missing associated documentation comment in .proto file."""

    def register_user(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_user_profile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserProfileServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register_user': grpc.unary_unary_rpc_method_handler(
                    servicer.register_user,
                    request_deserializer=user__profile__pb2.UserLogInfo.FromString,
                    response_serializer=user__profile__pb2.StatusResponse.SerializeToString,
            ),
            'get_user_profile': grpc.unary_unary_rpc_method_handler(
                    servicer.get_user_profile,
                    request_deserializer=user__profile__pb2.UserLogInfo.FromString,
                    response_serializer=user__profile__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user_profile.UserProfile', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user_profile.UserProfile', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserProfile(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def register_user(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_profile.UserProfile/register_user',
            user__profile__pb2.UserLogInfo.SerializeToString,
            user__profile__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_user_profile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_profile.UserProfile/get_user_profile',
            user__profile__pb2.UserLogInfo.SerializeToString,
            user__profile__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
