# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import money_transcation_pb2 as money__transcation__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in money_transcation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MoneyTransactonStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.deposit = channel.unary_unary(
                '/user_profile.MoneyTransacton/deposit',
                request_serializer=money__transcation__pb2.UserDepositRequest.SerializeToString,
                response_deserializer=money__transcation__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.withdraw = channel.unary_unary(
                '/user_profile.MoneyTransacton/withdraw',
                request_serializer=money__transcation__pb2.UserDepositRequest.SerializeToString,
                response_deserializer=money__transcation__pb2.TransactionResponse.FromString,
                _registered_method=True)


class MoneyTransactonServicer(object):
    """Missing associated documentation comment in .proto file."""

    def deposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def withdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MoneyTransactonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'deposit': grpc.unary_unary_rpc_method_handler(
                    servicer.deposit,
                    request_deserializer=money__transcation__pb2.UserDepositRequest.FromString,
                    response_serializer=money__transcation__pb2.TransactionResponse.SerializeToString,
            ),
            'withdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.withdraw,
                    request_deserializer=money__transcation__pb2.UserDepositRequest.FromString,
                    response_serializer=money__transcation__pb2.TransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user_profile.MoneyTransacton', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user_profile.MoneyTransacton', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MoneyTransacton(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def deposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_profile.MoneyTransacton/deposit',
            money__transcation__pb2.UserDepositRequest.SerializeToString,
            money__transcation__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def withdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_profile.MoneyTransacton/withdraw',
            money__transcation__pb2.UserDepositRequest.SerializeToString,
            money__transcation__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
