# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: money_transcation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'money_transcation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17money_transcation.proto\x12\x0cuser_profile\"I\n\x12UserDepositRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rpassword_hash\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"\x97\x01\n\x13TransactionResponse\x12:\n\x04\x63ode\x18\x01 \x01(\x0e\x32,.user_profile.TransactionResponse.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"3\n\nStatusCode\x12\x06\n\x02OK\x10\x00\x12\x12\n\x0eUSER_NOT_FOUND\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x32\xb2\x01\n\x0fMoneyTransacton\x12N\n\x07\x64\x65posit\x12 .user_profile.UserDepositRequest\x1a!.user_profile.TransactionResponse\x12O\n\x08withdraw\x12 .user_profile.UserDepositRequest\x1a!.user_profile.TransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'money_transcation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERDEPOSITREQUEST']._serialized_start=41
  _globals['_USERDEPOSITREQUEST']._serialized_end=114
  _globals['_TRANSACTIONRESPONSE']._serialized_start=117
  _globals['_TRANSACTIONRESPONSE']._serialized_end=268
  _globals['_TRANSACTIONRESPONSE_STATUSCODE']._serialized_start=217
  _globals['_TRANSACTIONRESPONSE_STATUSCODE']._serialized_end=268
  _globals['_MONEYTRANSACTON']._serialized_start=271
  _globals['_MONEYTRANSACTON']._serialized_end=449
# @@protoc_insertion_point(module_scope)
