# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: money_transcation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'money_transcation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17money_transcation.proto\x12\x0cuser_profile\"\\\n\x12UserDepositRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rpassword_hash\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x11\n\tuser_uuid\x18\x04 \x01(\t\"\x8d\x01\n\x0eStatusResponse\x12\x35\n\x04\x63ode\x18\x01 \x01(\x0e\x32\'.user_profile.StatusResponse.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"3\n\nStatusCode\x12\x06\n\x02OK\x10\x00\x12\x12\n\x0eUSER_NOT_FOUND\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x32\xa8\x01\n\x0fMoneyTransacton\x12I\n\x07\x64\x65posit\x12 .user_profile.UserDepositRequest\x1a\x1c.user_profile.StatusResponse\x12J\n\x08withdraw\x12 .user_profile.UserDepositRequest\x1a\x1c.user_profile.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'money_transcation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERDEPOSITREQUEST']._serialized_start=41
  _globals['_USERDEPOSITREQUEST']._serialized_end=133
  _globals['_STATUSRESPONSE']._serialized_start=136
  _globals['_STATUSRESPONSE']._serialized_end=277
  _globals['_STATUSRESPONSE_STATUSCODE']._serialized_start=226
  _globals['_STATUSRESPONSE_STATUSCODE']._serialized_end=277
  _globals['_MONEYTRANSACTON']._serialized_start=280
  _globals['_MONEYTRANSACTON']._serialized_end=448
# @@protoc_insertion_point(module_scope)
