/**
 * @fileoverview gRPC-Web generated client stub for user_profile
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v3.13.0
// source: money_transcation.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.user_profile = require('./money_transcation_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.user_profile.MoneyTransactonClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.user_profile.MoneyTransactonPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user_profile.UserDepositRequest,
 *   !proto.user_profile.TransactionResponse>}
 */
const methodDescriptor_MoneyTransacton_deposit = new grpc.web.MethodDescriptor(
  '/user_profile.MoneyTransacton/deposit',
  grpc.web.MethodType.UNARY,
  proto.user_profile.UserDepositRequest,
  proto.user_profile.TransactionResponse,
  /**
   * @param {!proto.user_profile.UserDepositRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user_profile.TransactionResponse.deserializeBinary
);


/**
 * @param {!proto.user_profile.UserDepositRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user_profile.TransactionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user_profile.TransactionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user_profile.MoneyTransactonClient.prototype.deposit =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user_profile.MoneyTransacton/deposit',
      request,
      metadata || {},
      methodDescriptor_MoneyTransacton_deposit,
      callback);
};


/**
 * @param {!proto.user_profile.UserDepositRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user_profile.TransactionResponse>}
 *     Promise that resolves to the response
 */
proto.user_profile.MoneyTransactonPromiseClient.prototype.deposit =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user_profile.MoneyTransacton/deposit',
      request,
      metadata || {},
      methodDescriptor_MoneyTransacton_deposit);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user_profile.UserDepositRequest,
 *   !proto.user_profile.TransactionResponse>}
 */
const methodDescriptor_MoneyTransacton_withdraw = new grpc.web.MethodDescriptor(
  '/user_profile.MoneyTransacton/withdraw',
  grpc.web.MethodType.UNARY,
  proto.user_profile.UserDepositRequest,
  proto.user_profile.TransactionResponse,
  /**
   * @param {!proto.user_profile.UserDepositRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user_profile.TransactionResponse.deserializeBinary
);


/**
 * @param {!proto.user_profile.UserDepositRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user_profile.TransactionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user_profile.TransactionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user_profile.MoneyTransactonClient.prototype.withdraw =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user_profile.MoneyTransacton/withdraw',
      request,
      metadata || {},
      methodDescriptor_MoneyTransacton_withdraw,
      callback);
};


/**
 * @param {!proto.user_profile.UserDepositRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user_profile.TransactionResponse>}
 *     Promise that resolves to the response
 */
proto.user_profile.MoneyTransactonPromiseClient.prototype.withdraw =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user_profile.MoneyTransacton/withdraw',
      request,
      metadata || {},
      methodDescriptor_MoneyTransacton_withdraw);
};


module.exports = proto.user_profile;

