/**
 * @fileoverview gRPC-Web generated client stub for service_game
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v3.13.0
// source: src/protos/service_game.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.service_game = require('./service_game_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.service_game.GameServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.service_game.GameServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.service_game.SpinRequest,
 *   !proto.service_game.SpinResult>}
 */
const methodDescriptor_GameService_GetResults = new grpc.web.MethodDescriptor(
  '/service_game.GameService/GetResults',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.service_game.SpinRequest,
  proto.service_game.SpinResult,
  /**
   * @param {!proto.service_game.SpinRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.service_game.SpinResult.deserializeBinary
);


/**
 * @param {!proto.service_game.SpinRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.service_game.SpinResult>}
 *     The XHR Node Readable Stream
 */
proto.service_game.GameServiceClient.prototype.getResults =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/service_game.GameService/GetResults',
      request,
      metadata || {},
      methodDescriptor_GameService_GetResults);
};


/**
 * @param {!proto.service_game.SpinRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.service_game.SpinResult>}
 *     The XHR Node Readable Stream
 */
proto.service_game.GameServicePromiseClient.prototype.getResults =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/service_game.GameService/GetResults',
      request,
      metadata || {},
      methodDescriptor_GameService_GetResults);
};


module.exports = proto.service_game;

